config/routes.rb
Offcampus::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :landlords
  resources :properties

  

  namespace :admin do
    resources :landlords
    resources :properties
  end

  root :to => 'pages#home'

  match '/dashboard' => 'landlords#dashboard', :as => :user_root

  match 'dashboard' => 'landlords#dashboard'

  devise_scope :user do
    get "sign_out", :to => "devise/sessions#destroy"
  end

  match '/list' => 'pages#list'

  match '/landing' => 'pages#landing'

  match '/js/properties' => 'properties#properties'

end

app/models/property.rb
class Property < ActiveRecord::Base
	attr_accessible :description, :address, :laundry, :price, :unit, :square_footage, :bedrooms, :landlord_id, :user_id, :featured, :photos_attributes, :summer, :utilities, :rooms, :parking

	validates :address, :presence => true
	validates :description, :presence => true
	validates :bedrooms, :presence => true, :numericality => { :only_integer => true }
	validates :square_footage, :presence => true, :numericality => { :only_integer => true }
	validates :price, :presence => true, :numericality => true

	belongs_to :landlord

	has_many :photos

	accepts_nested_attributes_for :photos, :allow_destroy => true, :reject_if => proc { |attributes| attributes['photo'].nil? and attributes['id'].blank? }

	def self.highest_price
		if @max_price == nil
			@max_price = Property.maximum("price")
		else
			return @max_price
		end
	end

	def featured_photo
		return nil if(photos.length == 0)

		photos.each do |photo|
			return photo if photo.main == true
		end

		return photos[0]
	end

	def has_photo?
		return false if photos == nil
		return photos.length > 0
	end

	def self.bedroom_counts
		Property.group("bedrooms").count()
	end

	def self.bedroom_counts_condensed
		counts = self.bedroom_counts

		counts[6] = 0 if counts[6] == nil

		counts.each do |count|
			counts[6] += count[1] if count[0] > 6
		end

		return counts
	end
end

app/controllers/admin/properties_controller.rb
class Admin::PropertiesController < ApplicationController
  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @properties }
    end
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @property = Property.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/new
  # GET /properties/new.json
  def new
    @property = Property.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/1/edit
  def edit
    @property = Property.find(params[:id])
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(params[:property])

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render json: @property, status: :created, location: @property }
      else
        format.html { render action: "new" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /properties/1
  # PUT /properties/1.json
  def update
    @property = Property.find(params[:id])

    respond_to do |format|
      if @property.update_attributes(params[:property])
        format.html { redirect_to :index, notice: 'Property was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property = Property.find(params[:id])
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all

    if user_signed_in?
      @user = User.find(current_user)
    end

    if(params[:layout] == 'false')
      render :layout => false
    else
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @properties }
      end
    end
  end

  def properties
    @properties = Property.all

    @highest_price = Property.highest_price

    respond_to do |format|
      format.js { render :layout => false }
    end
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @property = Property.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/new
  # GET /properties/new.json
  def new
    $counter = 0
    @property = Property.new
    @property.photos.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/1/edit
  def edit
    $counter = 0
    @property = Property.find(params[:id])
    @property.photos.build
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(params[:property])
    @property.featured = false
    @property.landlord_id = User.find(current_user).landlord.id
    
    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render json: @property, status: :created, location: @property }
      else
        format.html { render action: "new" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /properties/1
  # PUT /properties/1.json
  def update
    @property = Property.find(params[:id])

    respond_to do |format|
      if @property.update_attributes(params[:property])
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property = Property.find(params[:id])
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
	def add_photo_link(name)
		"<a href='#' class='add_photo btn'>#{name}</a>".html_safe
	end
end

app/views/properties/_form.haml
= form_for(@property, :html => { :multipart => true }) do |f|
  - if @property.errors.any?
    #error_explanation
      %h4
        = pluralize(@property.errors.count, "error")
        prohibited this property from being saved:
      %ul
        - @property.errors.full_messages.each do |msg|
          %li= msg
  %h4 Basic Info
  %ol
    %li
      = f.label :address
      = f.text_field :address
    %li
      = f.label :description
      = f.text_area :description
    %li
      = f.label :square_footage
      = f.text_field :square_footage, :size => 4
    %li
      = f.label :bedrooms, 'Number of Bedrooms'
      = f.text_field :bedrooms, :size => 2
    %li
      = f.label :rooms, 'Rooms'
      = f.text_field :rooms, :size => 2
  %h4 Additional Info
  %ol
    %li
      = f.label :laundry, 'Laundry Included?'
      = f.check_box :laundry
    %li
      = f.label :price, 'Price'
      $#{f.text_field :price, :size => 4}
      per
      \#{f.select :unit, options_for_select([ ['Month', 'month'], ['Year', 'year'], ['Semester', 'semester'] ])}
    %li
      = f.label :summer, 'Available for Summer'
      = f.check_box :summer
    %li
      = f.label :utilities, "Included utilities"
      = f.text_field :utilities
    %li
      = f.label :parking, 'Parking included?'
      = f.check_box :parking


  %h4 Property Photos

  %ol.photos
    = f.fields_for :photos do |photo_form|
      %li.photo
        - if not photo_form.object.new_record?
          %ol.forms
            %li.delete

              %a.delete_photo{:href => "#", :class => 'btn warning'} remove photo
              = photo_form.hidden_field :_destroy, :value => 0

            %li.featured_check
              = photo_form.label :main, "Feature this photo (only one)"
              = photo_form.check_box :main, :class => "featured"

            %li.preview
              - if not photo_form.object.new_record?
                = image_tag photo_form.object.photo.url(:medium)
        - if photo_form.object.new_record?
          %ol.forms
            %li 
              = photo_form.label :main, "Feature this photo"
              = photo_form.check_box :main, :class => "featured"

            %li
              = photo_form.file_field :photo, :class => 'btn'

    = add_photo_link('+ Add New Photo')
    .actions
      = f.submit

app/views/properties/edit.html.erb
<h3>Editing property</h3>

<%= render 'form' %>

<%= link_to 'Back to Dashboard', dashboard_path, :class => "btn" %>
<%= link_to 'Back to Listing', @property, :class => "btn" %>

app/views/properties/index.html.erb
<h1>Listing properties</h1>

<table>
  <tr>
    <th>Landlord</th>
    <th>Address</th>
    <th>Description</th>
    <th>Price</th>
    <th>Laundry</th>
    <th></th>
  </tr>

<% @properties.each do |property| %>
  <tr>
    <td><%= property.landlord.name %></td>
    <td><%= property.address %></td>
    <td><%= property.description %></td>
    <td><%= property.price %> a <%= property.unit %></td>
    <td><%= property.laundry ? 'included' : 'not included' %></td>
    <td>
      <% if user_signed_in? and property.landlord_id == @user.landlord.id %>
        <%= link_to 'Edit', edit_property_path(property) %>
        <%= link_to 'Destroy', property, confirm: 'Are you sure?', method: :delete %>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

app/views/properties/new.html.erb
<h1>Add Property</h1>

<%= render :partial => 'form', :locals => { :property => @property } %>

app/views/properties/properties.js.erb
$(document).ready(function() {
	$(".add_photo").click(function() {
		//$(this).before('<%= raw (render :partial => 'photo', :object => Photo.new).gsub("\n", "\\n") %>');

		// Extract the previous photo index
		var index = parseInt($(this).siblings('li.photo:last').find('input').attr('name').match(/[\d]+/)[0]);

		var photo_element = $(this).siblings('li.photo:last').clone();

		photo_element.find('input').each(function(i, input) {
			$(input).attr('name', $(input).attr('name').replace(index, index + 1));
		});

		photo_element.insertBefore($(this));

		return false;
	});

	$(".delete_photo").live('click', function() {
		$(this).siblings('input').val(1);
		$(this).parent().parent().parent().hide();

		return false;
	});

	$(".featured").live('click', function() {
		$(".featured").attr('checked', false);
		$(this).attr('checked', true);
	});


	if($(".sliderbar").length > 0) {
		$(".sliderbar").noUiSlider("init", {
			startMin: 0,
			startMax: 100,
			tracker: function() {
				update_sliderbar_readout();
			},
			change: function() {
				var prices = $(".sliderbar").noUiSlider("getValue");
				var bedrooms = $("#size_categories .active a:last").attr('rel');

				$.get("/list", {
					layout: false,
					low_price: Math.round(prices[0] * <%= @highest_price / 100 %>),
					high_price: Math.round(prices[1] * <%= @highest_price / 100 %>),
					bedrooms: bedrooms
				}, function(data) {
					$("section.listing").empty().html(data);
				});
			}
		});

		$(".sliderbar .noUi_sliderKnob").append("<div class='noUi_readout'></div>");

		update_sliderbar_readout();
	}

	$("#slides").slides({
	    preload: true,
	    preloadImage: 'img/loading.gif',
	    play: 5000,
	    pause: 2500,
	    hoverPause: true
  	});

  	$("#slides").show();

  	$("#size_categories li a").click(function () {
  		$("#size_categories li").removeClass('active');
  		$(this).parent().addClass('active');

  		var bedrooms = $(this).attr('rel');

		var prices = $(".sliderbar").noUiSlider("getValue");

  		if(bedrooms == '-1') {
	  		$.get("/list", {
	  			layout: false,
	  			low_price: Math.round(prices[0] * <%= @highest_price / 100 %>),
	  			high_price: Math.round(prices[1] * <%= @highest_price / 100 %>)
	  		}, function (data) {
	  			$("section.listing").empty().html(data);
	  		});
  		}
  		else {
	  		$.get("/list", {
	  			layout: false,
	  			bedrooms: bedrooms,
	  			low_price: Math.round(prices[0] * <%= @highest_price / 100 %>),
	  			high_price: Math.round(prices[1] * <%= @highest_price / 100 %>)
	  		}, function (data) {
	  			$("section.listing").empty().html(data);
	  		});
	  	}

  		return false;
  	});

  	$(".reset_filters").live('click', function() {
  		$(".sliderbar").noUiSlider("move", {
  			setTo: [0, 100]
  		});

		update_sliderbar_readout();

  		$("#size_categories li.active").removeClass('active');
  		$("#size_categories li:first").addClass('active');

  		$.get("/list", {
  				layout: false
  			}, function(data) {
  			$("section.listing").empty().html(data);
  		});
  	});

	var myOptions = {
	  center: new google.maps.LatLng(42.7958, -77.8172),
	  zoom: 15,
	  mapTypeId: google.maps.MapTypeId.ROADMAP
	};

	var map = new google.maps.Map(document.getElementById("big_map"), myOptions);


	var infowindow = new google.maps.InfoWindow({
		content: "hello world"
	});

  	<% @properties.each_with_index do |property, index| %>
  		add_address_marker('<%= property.address %>, Geneseo NY 14454', '<strong><%= property.address %></strong> \
  			<%= image_tag property.featured_photo.photo.url(:thumb) if property.has_photo? %> \
  			<p><%= link_to "read more", property %></p> \
  			', map);
  	<% end %>

	function add_address_marker(address, description, map) {
	  	var geocoder = new google.maps.Geocoder();

		geocoder.geocode( { 'address': address}, function(results, status) {
	      if (status == google.maps.GeocoderStatus.OK) {
	        var marker = new google.maps.Marker({
	            map: map,
	            position: results[0].geometry.location,
	            title: address
	        });

	        marker.setVisible(true);

	        google.maps.event.addListener(marker, "click", function() {
	        	infowindow.setContent(description);
	        	infowindow.open(map, this);
	        });
	      } else {
	        console.log("Geocode was not successful for the following reason: " + status);
	      }
	    });	
	}
});

function update_sliderbar_readout() {
	var prices = $(".sliderbar").noUiSlider("getValue");

	$(".sliderbar .noUi_lowerHandle .noUi_readout").text("$" + Math.round(prices[0] * <%= @highest_price %> / 100));
	$(".sliderbar .noUi_upperHandle .noUi_readout").text("$" + Math.round(prices[1] * <%= @highest_price %> / 100));
}

app/views/properties/show.haml
%h3.property-title= @property.address
- if @property.has_photo?
  #slides
    .slides_container
      - @property.photos.each do |photo|
        %div
          = image_tag photo.photo.url(:medium)
%dl.show
  %section
    %h4 Contact info
    %dt Owner:
    %dd= @property.landlord.name
    - if @property.landlord.hide_email == false
      %dt Email:
      %dd
        %a{:href => "mailto:#{@property.landlord.user.email}"}= @property.landlord.user.email
    %dt Phone:
    %dd= @property.landlord.phone
  %section
    %h4 Rent Details
    %dt Price:
    %dd
      $#{@property.price} per #{@property.unit}
    %dt Available over the Summer:
    %dd= @property.summer ? 'yes' : 'no'
  %section
    %h4 Property Info
    %dt Bedrooms:
    %dd= @property.bedrooms
    - if @property.rooms > 0
      %dt Rooms:
      %dd
    - if @property.square_footage != 0
      %dt Square Footage:
      %dd
        = @property.square_footage
        square feet
    %dt Parking:
    %dd= @property.parking ? 'yes' : 'no'
    %dt Laundry:
    %dd= @property.laundry ? 'included' : 'not included'
    - if @property.utilities != ''
      %dt Utilities:
      %dd= @property.utilities

%h4.wide Description

.description
  = @property.description
= link_to 'Back to Dashboard', dashboard_path, :class => "btn", :action => 'list'
= link_to 'Edit Listing', edit_property_path(@property), :class => "btn"