config/routes.rb
Offcampus::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :landlords
  resources :properties

  

  namespace :admin do
    resources :landlords
    resources :properties
  end

  root :to => 'pages#home'

  match '/dashboard' => 'landlords#dashboard', :as => :user_root

  match 'dashboard' => 'landlords#dashboard'

  devise_scope :user do
    get "sign_out", :to => "devise/sessions#destroy"
  end

  match '/list' => 'pages#list'

  match '/landing' => 'pages#landing'

  match '/js/properties' => 'properties#properties'

end

app/models/landlord.rb
class Landlord < ActiveRecord::Base
  attr_accessible :name, :email, :phone, :hide_email
  has_many :properties
  belongs_to :user
end

app/controllers/admin/landlords_controller.rb
class Admin::LandlordsController < ApplicationController
  # GET /landlords
  # GET /landlords.json
  def index
    @landlords = Landlord.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @landlords }
    end
  end

  # GET /landlords/1
  # GET /landlords/1.json
  def show
    @landlord = Landlord.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @landlord }
    end
  end

  # GET /landlords/new
  # GET /landlords/new.json
  def new
    @landlord = Landlord.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @landlord }
    end
  end

  # GET /landlords/1/edit
  def edit
    @landlord = Landlord.find(params[:id])
  end

  # POST /landlords
  # POST /landlords.json
  def create
    @landlord = Landlord.new(params[:landlord])

    respond_to do |format|
      if @landlord.save
        format.html { redirect_to @landlord, notice: 'Landlord was successfully created.' }
        format.json { render json: @landlord, status: :created, location: @landlord }
      else
        format.html { render action: "new" }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /landlords/1
  # PUT /landlords/1.json
  def update
    @landlord = Landlord.find(params[:id])

    respond_to do |format|
      if @landlord.update_attributes(params[:landlord])
        format.html { redirect_to @landlord, notice: 'Landlord was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /landlords/1
  # DELETE /landlords/1.json
  def destroy
    @landlord = Landlord.find(params[:id])
    @landlord.destroy

    respond_to do |format|
      format.html { redirect_to landlords_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/landlords_controller.rb
class LandlordsController < ApplicationController
	before_filter :authenticate_user!

	def dashboard
		@user = User.find(current_user);
		@landlord = @user.landlord;
	end

	# PUT /landlords/1
  	# PUT /landlords/1.json
	def update
		@landlord = Landlord.find(params[:id])

		respond_to do |format|
		  if @landlord.update_attributes(params[:landlord])
		    format.html { redirect_to :dashboard, notice: 'Your information was saved successfully.' }
		    format.json { head :no_content }
		  else
		    format.html { render action: "edit" }
		    format.json { render json: @landlord.errors, status: :unprocessable_entity }
		  end
		end
	end
end

app/helpers/landlords_helper.rb
module LandlordsHelper
end

app/views/admin/landlords/_form.html.erb
<%= form_for(@landlord) do |f| %>
  <% if @landlord.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@landlord.errors.count, "error") %> prohibited this landlord from being saved:</h2>

      <ul>
      <% @landlord.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='field'>
    <%= f.label :name %><br />
    <%= f.text_field :name %>

  </div>

  <div class='field'>
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>

  <div class='field'>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/landlords/edit.html.erb
<h1>Editing landlord</h1>

<%= render 'form' %>

<%= link_to 'Show', @landlord %> |
<%= link_to 'Back', landlords_path %>

app/views/admin/landlords/index.html.erb
<h1>Listing landlords</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Phone</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @landlords.each do |landlord| %>
  <tr>
    <td><%= landlord.name %></td>
    <td><%= landlord.phone %></td>
    <td><%= landlord.email %></td>
    <td><%= link_to 'Show', landlord %></td>
    <td><%= link_to 'Edit', edit_landlord_path(landlord) %></td>
    <td><%= link_to 'Destroy', landlord, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Landlord', new_landlord_path %>

app/views/admin/landlords/new.html.erb
<h1>New landlord</h1>

<%= render 'form' %>

<%= link_to 'Back', landlords_path %>

app/views/admin/landlords/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_landlord_path(@landlord) %> |
<%= link_to 'Back', landlords_path %>