config/routes.rb
Offcampus::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :landlords
  resources :properties

  

  namespace :admin do
    resources :landlords
    resources :properties
  end

  root :to => 'pages#home'

  match '/dashboard' => 'landlords#dashboard', :as => :user_root

  match 'dashboard' => 'landlords#dashboard'

  devise_scope :user do
    get "sign_out", :to => "devise/sessions#destroy"
  end

  match '/list' => 'pages#list'

  match '/landing' => 'pages#landing'

  match '/js/properties' => 'properties#properties'

end

app/views/pages/_list.haml
- properties.each_with_index do |property, index|
  - if index % 3 == 0
    .row
  .post
    - if user_signed_in? and property.landlord_id == @user.landlord.id
      = link_to 'edit info', edit_property_url(property), :class => 'edit'
    - if property.has_photo?
      %a{:href => "/properties/" + property.id.to_s}
        = image_tag property.featured_photo.photo.url(:medium), :class => 'house'
    .info
      %a{:href => "/properties/" + property.id.to_s}
        %h4= property.address
    %dl
      %dt Rooms:
      %dd= property.bedrooms
      %dt Parking:
      %dd= property.parking
      %dt Rent:
      %dd
        $#{property.price}
        %span.pay_period
          \/#{property.unit}
  - if index % 3 == 2
    </div>

app/views/pages/home.haml
%section
  %a{:href => '/list'}
    .view_by.students
      %span.students Students: 
      %br View All Listings
  %a{:href => '/landing'}
    .view_by.landlords
      %span.landlords Landlords:
      %br Add Your Property
%section
  #big_map

  %section
    - @featured.each_with_index do |property, index|
      - if index % 2 == 0
        .row

      %a{:href => 'properties/' + property.id.to_s }
        .post
          - if property.has_photo?
            = image_tag property.featured_photo.photo.url(:medium)

          %h4
            = property.address

          %p
            = property.bedrooms
            bedrooms

          %p
            = "$" + property.price.round.to_s
            per 
            = property.unit

    %p 

      = link_to 'Landlords, get your properties featured right here on the homepage!', { :action => 'list' }, { :class => 'view_by view_all' }

app/views/pages/landing.haml
#content.landing
  #content_wrapper
    %h1.tagline Find tenants with zero hassel.
    %h2.tagline By listing your properties with us, you gain:
    #right
      %a{:href => new_user_registration_path}
        %button#start Get Started
    %dl.reasons
      %dt.exp Exposure
      %dd Reach more students, ensuring all your rentals get filled.
      %dt.ctr Control
      %dd You manage your own properties online with our easy to use system.
      %dt.sec Security
      %dd With options to hide your personal info, we allow potential tenants to contact you, without sacrificing your identity online.
    #other
      %h2 We know students.
      %p.landing
        Our other Geneseo web service,
        = succeed "," do
          %a{:href => "http://www.knightscheduler.com", :target => "_blank"} Knight Scheduler
        was a great success, attracting nearly a quarter of the student body in just a few months.

app/views/pages/list.haml
- if @properties.length == 0 && @ajax == true
  %p
    Nothing found.
    %a.reset_filters.btn{:href => "#"} reset all filters
- else
  - if @ajax == true
    = render :partial => 'list', :locals => { :properties => @properties }
  - else
    %nav#size_categories
      %ul
        %li{:class => (@bedrooms == false ? 'active' : '') }
          %a{:href => "#", :rel =>  "-1"}
            All (#{@all.length})

        %li{:class => (@bedrooms == 0 ? 'active' : '')}
          %a{:href => "#", :rel => "0"} Studio
        
        %li{:class => (@bedrooms == 1 ? 'active' : '')}
          %a{:href => "#", :rel => "1"}
            1 Bedroom (#{@counts[1] || 0})
        
        %li{:class => (@bedrooms == 2 ? 'active' : '')}
          %a{:href => "#", :rel => "2"}
            2 Bedrooms (#{@counts[2] || 0})
        
        %li{:class => (@bedrooms == 3 ? 'active' : '')}
          %a{:href => "#", :rel => "3"}
            3 Bedrooms (#{@counts[3] || 0})
        
        %li{:class => (@bedrooms == 4 ? 'active' : '')}
          %a{:href => "#", :rel => "4"}
            4 Bedrooms (#{@counts[4] || 0})
        
        %li{:class => (@bedrooms == 5 ? 'active' : '')}
          %a{:href => "#", :rel => "5"}
            5 Bedrooms (#{@counts[5] || 0})
        
        %li{:class => (@bedrooms == true ? 'active' : '')}
          %a{:href => "#", :rel => "6"}
            6+ Bedrooms (#{@counts[6] || 0})
    #sort_categories
      .title
      .sliderbar
      .switch
        <input id="cal" name="view" type="radio" checked>
        <label for="cal">Fall + Spring</label>

        <input id="col" name="view" type="radio"> 
        <label for="col">Summer</label>
        
        <span class="switch-button"></span>
    %section.listing
      - if @properties.length == 0
        Nothing found.
        %a.reset_filters.btn{:href => '#'} reset all filters
      - else
        = render :partial => 'list', :locals => { :properties => @properties }