config/routes.rb
Offcampus::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :landlords
  resources :properties

  

  namespace :admin do
    resources :landlords
    resources :properties
  end

  root :to => 'pages#home'

  match '/dashboard' => 'landlords#dashboard', :as => :user_root

  match 'dashboard' => 'landlords#dashboard'

  devise_scope :user do
    get "sign_out", :to => "devise/sessions#destroy"
  end

  match '/list' => 'pages#list'

  match '/landing' => 'pages#landing'

  match '/js/properties' => 'properties#properties'

end

app/models/property.rb
class Property < ActiveRecord::Base
	attr_accessible :description, :address, :laundry, :price, :unit, :square_footage, :bedrooms, :landlord_id, :user_id, :featured, :photos_attributes, :summer, :utilities, :rooms, :parking

	validates :address, :presence => true
	validates :description, :presence => true
	validates :bedrooms, :presence => true, :numericality => { :only_integer => true }
	validates :square_footage, :presence => true, :numericality => { :only_integer => true }
	validates :price, :presence => true, :numericality => true

	belongs_to :landlord

	has_many :photos

	accepts_nested_attributes_for :photos, :allow_destroy => true, :reject_if => proc { |attributes| attributes['photo'].nil? and attributes['id'].blank? }

	def self.highest_price
		if @max_price == nil
			@max_price = Property.maximum("price")
		else
			return @max_price
		end
	end

	def featured_photo
		return nil if(photos.length == 0)

		photos.each do |photo|
			return photo if photo.main == true
		end

		return photos[0]
	end

	def has_photo?
		return false if photos == nil
		return photos.length > 0
	end

	def self.bedroom_counts
		Property.group("bedrooms").count()
	end

	def self.bedroom_counts_condensed
		counts = self.bedroom_counts

		counts[6] = 0 if counts[6] == nil

		counts.each do |count|
			counts[6] += count[1] if count[0] > 6
		end

		return counts
	end
end

app/controllers/admin/properties_controller.rb
class Admin::PropertiesController < ApplicationController
  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @properties }
    end
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @property = Property.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/new
  # GET /properties/new.json
  def new
    @property = Property.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/1/edit
  def edit
    @property = Property.find(params[:id])
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(params[:property])

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render json: @property, status: :created, location: @property }
      else
        format.html { render action: "new" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /properties/1
  # PUT /properties/1.json
  def update
    @property = Property.find(params[:id])

    respond_to do |format|
      if @property.update_attributes(params[:property])
        format.html { redirect_to :index, notice: 'Property was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property = Property.find(params[:id])
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all

    if user_signed_in?
      @user = User.find(current_user)
    end

    if(params[:layout] == 'false')
      render :layout => false
    else
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @properties }
      end
    end
  end

  def properties
    @properties = Property.all

    @highest_price = Property.highest_price

    respond_to do |format|
      format.js { render :layout => false }
    end
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @property = Property.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/new
  # GET /properties/new.json
  def new
    $counter = 0
    @property = Property.new
    @property.photos.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/1/edit
  def edit
    $counter = 0
    @property = Property.find(params[:id])
    @property.photos.build
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(params[:property])
    @property.featured = false
    @property.landlord_id = User.find(current_user).landlord.id
    
    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render json: @property, status: :created, location: @property }
      else
        format.html { render action: "new" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /properties/1
  # PUT /properties/1.json
  def update
    @property = Property.find(params[:id])

    respond_to do |format|
      if @property.update_attributes(params[:property])
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property = Property.find(params[:id])
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
	def add_photo_link(name)
		"<a href='#' class='add_photo btn'>#{name}</a>".html_safe
	end
end

app/views/admin/properties/_form.haml
= form_for(@property) do |f|
  - if @property.errors.any?
    #error_explanation
      %h3
        = pluralize(@property.errors.count, "error")
        prohibited this property from being saved:
      %ul
        - @property.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :square_footage
    = f.text_field :square_footage, :size => 3
  .field
    = f.label :bedrooms, 'Number of Bedrooms'
    = f.text_field :bedrooms, :size => 2
  .field
    = f.label :price, 'Price'
    $#{f.text_field :price, :size => 4}
    per
    \#{f.select :unit, options_for_select([ ['Month', 'month'], ['Year', 'year'], ['Semester', 'semester'] ])}
  .field
    = f.label :laundry, 'Laundry Included?'
    = f.check_box :laundry
  .field
    = f.label :landlord_id, 'Landlord'
    = collection_select :property, :landlord_id, Landlord.all, :id, :name
  .field
    = f.label :featured, 'Featured'
    = f.check_box :featured
  .actions
    = f.submit

app/views/admin/properties/edit.html.erb
<h3>Editing property</h3>

<%= render 'form' %>

<%= link_to 'Show', @property, { :class => btn } %> |
<%= link_to 'Back', properties_path, { :class => btn } %>

app/views/admin/properties/index.html.erb
<h1>Listing properties</h1>

<table>
  <tr>
    <th>Landlord</th>
    <th>Address</th>
    <th>Description</th>
    <th>Price</th>
    <th>Laundry</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @properties.each do |property| %>
  <tr>
    <td><%= property.landlord.name %></td>
    <td><%= property.address %></td>
    <td><%= property.description %></td>
    <td><%= property.price %> per <%= property.unit %></td>
    <td><%= property.laundry ? 'included' : 'not included' %></td>
    <td><%= link_to 'Show', property %></td>
    <td><%= link_to 'Edit', :action => 'edit', :id => property.id %></td>
    <td><%= link_to 'Destroy', property, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Property', new_property_path %>

app/views/admin/properties/new.html.erb
<h3>New property</h3>

<%= render 'form' %>

<%= link_to 'Back', properties_path %>

app/views/admin/properties/show.html.erb
<h3><%= @property.address %></h3>
<dl>
	<dt>Landlord:</dt>
	<dd><%= @property.landlord.name %></dd>

	<dt>Phone:</dt>
	<dd><%= @property.landlord.phone %></dd>

	<dt>Email:</dt>
	<dd><%= @property.landlord.email %></dd>

	<dt>Laundry included:</dt>
	<dd><%= @property.laundry ? 'yes' : 'no' %></dd>

	<dt>Price:</dt>
	<dd>$<%= @property.price %> per <%= @property.unit %></dd>

	<dt>Number of Bedrooms:</dt>
	<dd><%= @property.bedrooms %></dd>

	<dt>Square Footage:</dt>
	<dd><%= @property.square_footage %></dd>
</dl>

<div class='description'>
	<%= @property.description %>
</div>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>